%YAML 1.1
---
backend:
  name: git-gateway
  branch: main
media_folder: "images/uploads"
collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Content"
        name: "content"
        file: "site/content.json"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: string}
          - {label: Work, name: work, widget: string}         
          - {label: Contact, name: contact, widget: string}